"""Generate Theos tweak scaffolds + ranked targets from annotated dumps.

Phase 3 substrate surface: dump → ranked Music types → starter Theos project.
Follows Music27's safe pattern — hook UIKit bases, filter by class_getName.
No live FOVO; addresses from dumps are not stable across launches.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .api import PeekSession


# Field name / type hints that usually matter for UI tweaks.
_INTERESTING = re.compile(
    r"(button|label|artwork|title|action|stack|bar|player|queue|view|gesture|menu|"
    r"image|header|footer|tab|lyric|transport|control|chrome|dock)",
    re.I,
)


@dataclass
class TargetScore:
    type_name: str
    objc_class: str
    role: str
    score: int
    screen_strings: list[str]
    interesting_fields: list[str]
    field_count: int

    def as_dict(self) -> dict[str, Any]:
        return {
            "type": self.type_name,
            "objc_class": self.objc_class,
            "role": self.role,
            "score": self.score,
            "field_count": self.field_count,
            "screen_strings": list(self.screen_strings),
            "interesting_fields": list(self.interesting_fields),
        }


def _short(name: str) -> str:
    return name.rsplit(".", 1)[-1].split("<", 1)[0]


def rank_targets(session: PeekSession, limit: int = 20) -> list[TargetScore]:
    """Score dump nodes for tweakability (Music types + strings + field hints)."""
    seen: dict[str, TargetScore] = {}
    for node in session.nodes:
        type_name = (
            node.get("offline_type")
            or node.get("type")
            or node.get("objc_class")
            or "?"
        )
        objc = node.get("objc_class") or type_name
        strings = [str(s) for s in (node.get("screen_strings") or []) if s]
        fields = node.get("offline_fields") or []
        interesting: list[str] = []
        for f in fields:
            name = str(f.get("name") or "")
            typ = str(f.get("type") or "")
            if _INTERESTING.search(name) or _INTERESTING.search(typ):
                interesting.append(name)
        score = len(strings) * 3 + len(interesting) * 2 + min(len(fields), 20)
        if type_name.startswith("MusicApplication.") or "Music" in type_name:
            score += 10
        role = str(node.get("role") or "")
        if "controller" in role:
            score += 4
        prev = seen.get(type_name)
        if prev is None or score > prev.score:
            seen[type_name] = TargetScore(
                type_name=type_name,
                objc_class=str(objc),
                role=role,
                score=score,
                screen_strings=strings[:12],
                interesting_fields=interesting[:16],
                field_count=len(fields),
            )
    ranked = sorted(seen.values(), key=lambda t: (-t.score, t.type_name))
    return ranked[:limit]


def format_targets(targets: list[TargetScore]) -> str:
    lines = ["# SwiftPeek tweak targets (ranked)", ""]
    for i, t in enumerate(targets, 1):
        lines.append(f"## {i}. {t.type_name}  (score {t.score})")
        lines.append(f"- objc_class: `{t.objc_class}`")
        lines.append(f"- role: `{t.role}` · fields: {t.field_count}")
        if t.screen_strings:
            lines.append(
                f"- screen: {', '.join(repr(s) for s in t.screen_strings[:8])}"
            )
        if t.interesting_fields:
            lines.append(
                f"- interesting: {', '.join(t.interesting_fields[:12])}"
            )
        lines.append("")
    return "\n".join(lines)


def _sanitize_pkg(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "", name)
    if not s:
        s = "PeekTweak"
    if s[0].isdigit():
        s = "T" + s
    return s


def _select_targets(
    targets: list[TargetScore],
    filter_substr: str | None,
    max_hooks: int = 5,
) -> list[TargetScore]:
    if filter_substr:
        n = filter_substr.lower()
        chosen = [
            t
            for t in targets
            if n in t.type_name.lower() or n in t.objc_class.lower()
        ]
        if chosen:
            return chosen[:max_hooks]
    return targets[:max_hooks]


def generate_tweak_x(
    tweak_name: str,
    targets: list[TargetScore],
    *,
    filter_substr: str | None = None,
) -> str:
    """Emit a single %hook UIViewController with class-name filters."""
    chosen = _select_targets(targets, filter_substr)
    if not chosen:
        chosen = targets[:3]

    body = [
        "// Auto-generated by SwiftPeek scaffold — starting point only.",
        "// Pattern matches Music27: hook UIKit bases, filter by class name.",
        "// Dump addresses are NOT stable across launches — use class + field names.",
        "#import <UIKit/UIKit.h>",
        "#import <objc/runtime.h>",
        "#import <string.h>",
        "",
        "static BOOL PeekClassMatches(Class cls, const char *needle) {",
        "    if (!cls || !needle) return NO;",
        "    const char *n = class_getName(cls);",
        "    return n && strstr(n, needle) != NULL;",
        "}",
        "",
    ]
    for t in chosen:
        token = _short(t.type_name)
        body.append(f"// Target: {t.type_name}")
        if t.screen_strings:
            body.append(f"// screen: {', '.join(t.screen_strings[:6])}")
        for f in t.interesting_fields[:10]:
            body.append(f"// field: {f}")
        body.append("")

    body += [
        "%hook UIViewController",
        "- (void)viewDidAppear:(BOOL)animated {",
        "    %orig;",
        "    Class cls = object_getClass(self);",
    ]
    for t in chosen:
        token = _short(t.type_name)
        body += [
            f'    if (PeekClassMatches(cls, "{token}")) {{',
            f'        NSLog(@"[{tweak_name}] {token} %p", self);',
            f"        // TODO: customize {token}",
            f'        // Example: id art = [self valueForKey:@"artworkView"];',
            "    }",
        ]
    body += [
        "}",
        "%end",
        "",
    ]
    return "\n".join(body)


def write_scaffold(
    session: PeekSession,
    out_dir: Path,
    *,
    name: str = "PeekMusicTweak",
    bundle_id: str = "com.kolby.peekmusic",
    filter_substr: str | None = None,
    limit: int = 12,
) -> Path:
    """Write a minimal Theos project under out_dir. Returns the project root."""
    tweak = _sanitize_pkg(name)
    pkg = bundle_id if bundle_id else f"com.kolby.{tweak.lower()}"
    root = Path(out_dir)
    src = root / "src"
    src.mkdir(parents=True, exist_ok=True)

    targets = rank_targets(session, limit=limit)
    (root / "TARGETS.md").write_text(format_targets(targets), encoding="utf-8")
    (root / "src" / "Tweak.x").write_text(
        generate_tweak_x(tweak, targets, filter_substr=filter_substr),
        encoding="utf-8",
    )

    (root / f"{tweak}.plist").write_text(
        "{\n"
        "\tFilter = {\n"
        "\t\tBundles = (\n"
        '\t\t\t"com.apple.Music"\n'
        "\t\t);\n"
        "\t\tExecutables = (\n"
        '\t\t\t"Music"\n'
        "\t\t);\n"
        "\t};\n"
        "}\n",
        encoding="utf-8",
    )

    (root / "Makefile").write_text(
        "\n".join(
            [
                "TARGET := iphone:clang:16.5:15.0",
                "ARCHS = arm64 arm64e",
                "INSTALL_TARGET_PROCESSES = Music",
                "THEOS_PACKAGE_SCHEME ?= rootless",
                "",
                "include $(THEOS)/makefiles/common.mk",
                "",
                f"TWEAK_NAME = {tweak}",
                f"{tweak}_FILES = src/Tweak.x",
                f"{tweak}_CFLAGS = -fobjc-arc -Wno-unused-variable",
                f"{tweak}_FRAMEWORKS = UIKit Foundation",
                "",
                "include $(THEOS_MAKE_PATH)/tweak.mk",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    (root / "control").write_text(
        "\n".join(
            [
                f"Package: {pkg}",
                f"Name: {tweak}",
                "Depends: mobilesubstrate",
                "Version: 0.0.1",
                "Architecture: iphoneos-arm64",
                "Description: Scaffold from SwiftPeek dump — Music-only. Edit src/Tweak.x.",
                "Maintainer: ma6x9x",
                "Author: ma6x9x",
                "Section: Tweaks",
                "",
            ]
        ),
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        "\n".join(
            [
                f"# {tweak}",
                "",
                "Scaffold generated by SwiftPeek from a live Music dump + offline field catalog.",
                "",
                "## Build (Dopamine / rootless)",
                "",
                "```bash",
                "make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless",
                "```",
                "",
                "## Next",
                "",
                "1. Read `TARGETS.md` — pick a high-score type.",
                "2. Edit `src/Tweak.x` TODO blocks (class-name filtered `UIViewController` hook).",
                "3. Use offline field names from TARGETS / `swiftpeek fields` for `valueForKey:` experiments.",
                "4. Keep SwiftPeek **Dump Field Meta** off on device while developing.",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return root
